#ifndef APP_FSM_STATE_DEFS_H
#define APP_FSM_STATE_DEFS_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    APP_FSM_STATE_INIT = 0,
    APP_FSM_STATE_BOOT,
    APP_FSM_STATE_IDLE,
    APP_FSM_STATE_DEBUG_POLL,
    APP_FSM_STATE_HOUSEKEEPING_INIT,
    APP_FSM_STATE_HOUSEKEEPING_SNAPSHOT,
    APP_FSM_STATE_HOUSEKEEPING_ROTATE,
    APP_FSM_STATE_POWER_INIT,
    APP_FSM_STATE_POWER_WAIT_REQUEST,
    APP_FSM_STATE_METER_INIT,
    APP_FSM_STATE_METER_WAIT_TRIGGER,
    APP_FSM_STATE_METER_SEND_REQUEST,
    APP_FSM_STATE_METER_PARSE_REPLY,
    APP_FSM_STATE_NFC_INIT,
    APP_FSM_STATE_NFC_WAIT_EVENT,
    APP_FSM_STATE_NFC_EXCHANGE,
    APP_FSM_STATE_AUX_INIT,
    APP_FSM_STATE_AUX_TRIGGER_MEASURE,
    APP_FSM_STATE_AUX_READ_RESULT,
    APP_FSM_STATE_NBIOT_INIT,
    APP_FSM_STATE_NBIOT_DECIDE_WAKE,
    APP_FSM_STATE_NBIOT_POWER_ON,
    APP_FSM_STATE_NBIOT_EXCHANGE_AT,
    APP_FSM_STATE_SERVER_INIT,
    APP_FSM_STATE_SERVER_PREPARE_PACKET,
    APP_FSM_STATE_SERVER_REQUEST_SEND,
    APP_FSM_STATE_RTC_INIT,
    APP_FSM_STATE_RTC_WAKE_SERVICE,
    APP_FSM_STATE_RTC_APPLY_SYNC,
    APP_FSM_STATE_FAULT,
    MAX_APP_FSM_STATE
}APP_FSM_STATE_t;

#ifdef __cplusplus
}
#endif

#endif /* APP_FSM_STATE_DEFS_H */
